@Library('my-shared-library') _  // Load the shared library

pipeline {
    agent { label 'jenkins-slave' }

    environment {
        DOCKER_IMAGE = 'docker.io/ahmedmaher07/project'
        DEPLOYMENT_YAML = 'deployment.yaml'
    }

    stages {
        stage('Checkout') {
            steps {
                checkoutStage()  // Calls the checkoutStage.groovy function
            }
        }

        stage('Unit Test') {
            steps {
                unitTestStage()  // Calls the unitTestStage.groovy function
            }
        }

        stage('Build') {
            steps {
                buildStage()  // Calls the buildStage.groovy function
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sonarQubeStage()  // Calls the sonarQubeStage.groovy function
            }
        }

        stage('Login to Docker Hub') {
            steps {
                dockerLoginStage()  // Calls the dockerLoginStage.groovy function
            }
        }

        stage('Build Docker Image') {
            steps {
                dockerBuildStage()  // Calls the dockerBuildStage.groovy function
            }
        }

        stage('Push Docker Image') {
            steps {
                dockerPushStage()  // Calls the dockerPushStage.groovy function
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                deployStage('/home/ubuntu/jenkins/.kube/config', DEPLOYMENT_YAML)  // Calls the deployStage.groovy function
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed. Please check the logs for details."
        }
    }
}
