@Library('my-shared-library') _

pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'docker.io/ahmedmaher07/project'
        DEPLOYMENT_YAML = 'deployment.yaml'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkoutStage(
                        $class: 'GitSCM',
                        gitUrl: 'https://github.com/wolf452/CloudDevOpsProject.git',
                        gitBranch: 'main'
                    )
                }
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    unitTestStage()
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    buildStage()
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    sonarQubeStage()
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    dockerLoginStage()
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerBuildStage(env.DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dockerPushStage(env.DOCKER_IMAGE)
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    deployStage(env.DEPLOYMENT_YAML)
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed. Please check the logs for details."
        }
    }
}
