@Library('my-shared-library') _

pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'docker.io/ahmedmaher07/project'
        DEPLOYMENT_YAML = 'deployment.yaml'
    }

    stages {
        stage('Checkout') {
            step {
                checkoutStage(
                     $class: 'GitSCM',
                    gitUrl: 'https://github.com/wolf452/CloudDevOpsProject.git',
                    gitBranch: 'main'
                )
            }
        }

        stage('Unit Test') {
            step {
                unitTestStage()
            }
        }

        stage('Build') {
            step {
                buildStage()
            }
        }

        stage('SonarQube Analysis') {
            step {
                sonarQubeStage()
            }
        }

        stage('Login to Docker Hub') {
            step {
                dockerLoginStage()
            }
        }

        stage('Build Docker Image') {
            step {
                dockerBuildStage(env.DOCKER_IMAGE)
            }
        }

        stage('Push Docker Image') {
            step {
                dockerPushStage(env.DOCKER_IMAGE)
            }
        }

        stage('Deploy to Kubernetes') {
            step {
                deployStage(env.DEPLOYMENT_YAML)
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed. Please check the logs for details."
        }
    }
}
